export class NtUser {
	public ntUserAdhar: any;
	public ntUserAuth: any;
	public ntUserAuthdby: any;
	public ntUserBranch: any;
	public ntUserCaddress: any;
	public ntUserContrycode: any;
	public ntUserCreatedby: any;
	public ntUserCreated: any;
	public ntUserDob: any;
	public ntUserEmail: any;
	public ntUserFname: any;
	public ntUserGroup: any;
	public ntUserIcpwd: any;
	public ntUserId: any;
	public ntUserLevel: any;
	public ntUserLname: any;
	public ntUserMname: any;
	public ntUserMobile: any;
	public ntUserPaddress: any;
	public ntUserPan: any;
	public ntUserPwd: any;
	public ntUserStatus: any;
	public ntUserType: any;
	public ntAgencyCode: any;
	public ntUserVerfication: any;
	public ntUserNative: any;
	public ntCountrycode: any;
}
